config/routes.rb
ReportApp::Application.routes.draw do

  resources :products

  match 'reports/updated_at' => 'reports#updated_at'
  match 'reports/:id/update_report' => 'reports#update_report'
  
  match 'report_lines/updated_at' => 'report_lines#updated_at'
  match 'report_lines/create_new' => 'report_lines#create_new'
  
  

  resources :users

  resources :report_lines

  resources :reports

end

app/models/report_line.rb
class ReportLine < ActiveRecord::Base

	belongs_to :report
	
	validates_presence_of :report_id, :pk, :voie
	
end

app/controllers/report_lines_controller.rb
class ReportLinesController < ApplicationController
  # GET /report_lines
  # GET /report_lines.xml
  def index
    @report_lines = ReportLine.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @report_lines }
      format.json { render :json => @report_lines }
    end
  end
 
  def updated_at
      render :text => ReportLine.maximum('updated_at').strftime('%Y-%m-%d %H:%M:%S') 
  end
  # GET /report_lines/1
  # GET /report_lines/1.xml
  def show
    @report_line = ReportLine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @report_line }
      format.json { render :json => @report_line }
    end
  end

  def create_new
  	report_id = params[:report_id]
  	pk= 	params[:pk]
  	lat=	params[:lat]
  	lon=	params[:lon]
  	voie= 	params[:voie]
  	file= 	params[:file]
  	conso= 	params[:conso]
  	
  	product_name = params[:product_name]
  	product_price= params[:product_price]
  	
    @report_line = ReportLine.new( :report_id => report_id, :pk => pk, :lat => lat, :lon => lon, :voie => voie, :file => file, :conso => conso, :product_name => product_name, :product_price => product_price )

    if @report_line.save
    	render :text => "OK"
    else
    	render :text => "Error"
    end
  end

  # GET /report_lines/new
  # GET /report_lines/new.xml
  def new
    @report_line = ReportLine.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @report_line }
    end
  end

  # GET /report_lines/1/edit
  def edit
    @report_line = ReportLine.find(params[:id])
  end

  # POST /report_lines
  # POST /report_lines.xml
  def create
    @report_line = ReportLine.new(params[:report_line])

    respond_to do |format|
      if @report_line.save
        format.html { redirect_to(@report_line, :notice => 'Report line was successfully created.') }
        format.xml  { render :xml => @report_line, :status => :created, :location => @report_line }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @report_line.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /report_lines/1
  # PUT /report_lines/1.xml
  def update
    @report_line = ReportLine.find(params[:id])

    respond_to do |format|
      if @report_line.update_attributes(params[:report_line])
        format.html { redirect_to(@report_line, :notice => 'Report line was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @report_line.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /report_lines/1
  # DELETE /report_lines/1.xml
  def destroy
    @report_line = ReportLine.find(params[:id])
    @report_line.destroy

    respond_to do |format|
      format.html { redirect_to(report_lines_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/report_lines_helper.rb
module ReportLinesHelper
end

app/views/report_lines/_form.html.erb
<%= simple_form_for(@report_line) do |f| %>
  <% if @report_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report_line.errors.count, "error") %> prohibited this report_line from being saved:</h2>

      <ul>
      <% @report_line.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :report_id %>
    <%= f.input :pk %>
    <%= f.input :lat %>
    <%= f.input :lon %>
    <%= f.input :voie %>
    <%= f.input :file, :collection => ["G","D"], :as => :radio %>
    <%= f.input :conso %>
    <%= f.input :product_name %>
    <%= f.input :product_price %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/report_lines/edit.html.erb
<h1>Editing report_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @report_line %> |
<%= link_to 'Back', report_lines_path %>

app/views/report_lines/index.html.erb
<h1>Listing report_lines</h1>

<table>
  <tr>
    <th>Report</th>
    <th>Pk</th>
    <th>Voie</th>
    <th>File</th>
    <th>Conso</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @report_lines.each do |report_line| %>
  <tr>
    <td><%= report_line.report_id %></td>
    <td><%= report_line.pk %></td>
    <td><%= report_line.voie %></td>
    <td><%= report_line.file %></td>
    <td><%= report_line.conso %></td>
    <td><%= link_to 'Show', report_line %></td>
    <td><%= link_to 'Edit', edit_report_line_path(report_line) %></td>
    <td><%= link_to 'Destroy', report_line, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report line', new_report_line_path %>

app/views/report_lines/new.html.erb
<h1>New report_line</h1>

<%= render 'form' %>

<%= link_to 'Back', report_lines_path %>

app/views/report_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Report:</b>
  <%= @report_line.report_id %>
</p>

<p>
  <b>Pk:</b>
  <%= @report_line.pk %>
</p>

<p>
  <b>Voie:</b>
  <%= @report_line.voie %>
</p>

<p>
  <b>File:</b>
  <%= @report_line.file %>
</p>

<p>
  <b>Conso:</b>
  <%= @report_line.conso %>
</p>


<%= link_to 'Edit', edit_report_line_path(@report_line) %> |
<%= link_to 'Back', report_lines_path %>