config/routes.rb
ReportApp::Application.routes.draw do

  resources :products

  match 'reports/updated_at' => 'reports#updated_at'
  match 'reports/:id/update_report' => 'reports#update_report'
  
  match 'report_lines/updated_at' => 'report_lines#updated_at'
  match 'report_lines/create_new' => 'report_lines#create_new'
  
  

  resources :users

  resources :report_lines

  resources :reports

end

app/models/report.rb
class Report < ActiveRecord::Base

	has_many :report_lines, :dependent => :destroy
	belongs_to :user
	
	validates_presence_of :user_id, :client, :chantier

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.xml
  def index
    @reports = Report.find(:all, :order => "updated_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reports }
      format.json { render :json => @reports.to_json(:include => [:report_lines]) }
    end
  end

  def updated_at
      render :text => Report.maximum('updated_at').strftime('%Y-%m-%d %H:%M:%S') 
  end	  

  # GET /reports/1
  # GET /reports/1.xml
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @report }
      format.json { render :json => @report.to_json(:include => [:report_lines]) }
    end
  end

  # GET /reports/new
  # GET /reports/new.xml
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.xml
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to(@report, :notice => 'Report was successfully created.') }
        format.xml  { render :xml => @report, :status => :created, :location => @report }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.xml
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to(@report, :notice => 'Report was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @report.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update_report
  	@report = Report.find(params[:id])
	submitted= 		params[:submitted]
  	temperature= 	params[:temperature]
  	sky= 			params[:sky_state]
  	
    if @report.update_attributes(:submitted => submitted,:temperature => temperature, :sky_state => sky)
    	render :text => "OK"
    else
    	render :text => "Error"
    end
  end
  
  # DELETE /reports/1
  # DELETE /reports/1.xml
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to(reports_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= simple_form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.association :user, :label_method => lambda { |user| "#{user.name}" }, :label => "Utilisateur" %>
    <%= f.input :client %>
    <%= f.input :chantier, :label => "Site" %>
    <%= f.input :isNight , :label => "Nuit?" %>
    <%= f.input :temperature, :label => "Température"  %>
    <%= f.input :sky_state, :label => "Temps" %>

  <div class="actions">
    <%= f.button :submit, :value => "Enregistrer" %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Modification du rapport</h1>

<%= render 'form' %>

<%= link_to 'Voir', @report %> |
<%= link_to 'Retour', reports_path %>

app/views/reports/index.html.erb
<table>
  <tr>
    <th>Utilisateur</th>
    <th>Client</th>
    <th>Site</th>
    <th>Nuit?</th>
    <th>Température</th>
    <th>Temps</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= User.find(report.user_id).name %></td>
    <td><%= report.client %></td>
    <td><%= report.chantier %></td>
    <td><%= "Oui" if report.isNight %></td>
    <td><%= report.temperature %></td>
    <td><%= report.sky_state %></td>
    <td><%= link_to 'Voir', report %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouveau Rapport', new_report_path %>

app/views/reports/new.html.erb
<h1>Nouveau rapport</h1>

<%= render 'form' %>

<%= link_to 'Retour', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>
<div class="span-12">
	<p>
	  <b>Utilisateur:</b>
	  <%= User.find(@report.user_id).name %>
	</p>

	<p>
	  <b>Client:</b>
	  <%= @report.client %>
	</p>

	<p>
	  <b>Site:</b>
	  <%= @report.chantier %>
	</p>
	<p>
	  <b>Envoyé ? : </b>
	  <%= "OUI" if @report.submitted %>
	</p>
</div>

<div class="span-12 last">
	<p>
	  <b>Nuit ?:</b>
	  <%= 'Oui' if @report.isNight %>
	</p>

	<p>
	  <b>Température:</b>
	  <%= @report.temperature %>
	</p>

	<p>
	  <b>Temps:</b>
	  <%= @report.sky_state %>
	</p>

	<p>
	  <b>Modifié_le:</b>
	  <%= @report.updated_at %>
	</p>
</div>

<%= link_to 'Modifier', edit_report_path(@report) %> 
<br>
<hr>
<br>

<h3>Détails</h3>
<table>
<th>PK</th>
<th>Latitude</th>
<th>Longitude</th>
<th>Voie</th>
<th>File</th>
<th>Consommation</th>
<th>Produit</th>
<th>Prix</th>
<th>Modifié_le</th>

<% for l in @report.report_lines %>
	<tr>
		<td><%= l.pk %></td>
		<td><%= l.lat %></td>
		<td><%= l.lon %></td>
		<td><%= l.voie %></td>
		<td><%= l.file %></td>
		<td><%= l.conso %></td>
		<td><%= l.product_name %></td>
		<td><%= l.product_price %></td>
		<td><%= l.updated_at %></td> 
	</tr>
<% end %>
</table>